In [1]:
import pandas as pd

## Load the JSON file that you created in the previous exercise into a dataframe
* set CarNumber as the index column

In [60]:
df = pd.read_json("../data/auto.json")
df.set_index("CarNumber", inplace=True)

df

              Refund         Fines    Make    Model
CarNumber
Y163O8161RUS       2   3200.000000    Ford    Focus
E432XX77RUS        1   6500.000000  Toyota    Camry
7184TT36RUS        1   2100.000000    Ford    Focus
X582HE161RUS       2   2000.000000    Ford    Focus
92918M178RUS       1   5700.000000    Ford    Focus
...              ...           ...     ...      ...
Y163O8161RUS       2   1600.000000    Ford    Focus
M0309X197RUS       1  22300.000000    Ford    Focus
O673E8197RUS       2    600.000000    Ford    Focus
8610T8154RUS       1   2000.000000    Ford    Focus
H419XE197RUS       2   8594.586466  Toyota  Corolla

[725 rows x 4 columns]

## Make the following selects
* display the rows only where the fines are more than 2,100
* display the rows only where the fines are more than 2,100 and the refund equals 2
* display the rows only where the models are from the list: [’Focus’, ’Corolla’]
* display the rows only where the car number is from the list: [’Y7689C197RUS’, ’92928M178RUS’, ’7788KT197RUS’, ’H115YO163RUS’, ’X758HY197RUS’]

In [12]:
df[df["Fines"] > 2100]

              Refund         Fines        Make    Model
CarNumber
Y163O8161RUS       2   3200.000000        Ford    Focus
E432XX77RUS        1   6500.000000      Toyota    Camry
92918M178RUS       1   5700.000000        Ford    Focus
H234YH197RUS       2   6000.000000        Ford    Focus
E40577152RUS       1   8594.586466        Ford    Focus
...              ...           ...         ...      ...
O718MM163RUS       2   8594.586466        Ford    Focus
7065C8197RUS       2  11400.000000  Volkswagen   Passat
O22097197RUS       1  24300.000000        Ford    Focus
M0309X197RUS       1  22300.000000        Ford    Focus
H419XE197RUS       2   8594.586466      Toyota  Corolla

[455 rows x 4 columns]

In [15]:
df[(df["Fines"] > 2100) & (df["Refund"] == 2)]

              Refund         Fines        Make    Model
CarNumber
Y163O8161RUS       2   3200.000000        Ford    Focus
H234YH197RUS       2   6000.000000        Ford    Focus
707987163RUS       2   2200.000000        Ford    Focus
K330T8197RUS       2   8200.000000       Skoda  Octavia
M592CH197RUS       2   8594.586466       Skoda  Octavia
...              ...           ...         ...      ...
O136HO197RUS       2   7800.000000      Toyota  Corolla
O68897197RUS       2  12300.000000        Ford    Focus
O718MM163RUS       2   8594.586466        Ford    Focus
7065C8197RUS       2  11400.000000  Volkswagen   Passat
H419XE197RUS       2   8594.586466      Toyota  Corolla

[309 rows x 4 columns]

In [17]:
df.loc[(df["Model"] == "Focus") | (df["Model"] == "Corolla")]

              Refund         Fines    Make    Model
CarNumber
Y163O8161RUS       2   3200.000000    Ford    Focus
7184TT36RUS        1   2100.000000    Ford    Focus
X582HE161RUS       2   2000.000000    Ford    Focus
92918M178RUS       1   5700.000000    Ford    Focus
H234YH197RUS       2   6000.000000    Ford    Focus
...              ...           ...     ...      ...
Y163O8161RUS       2   1600.000000    Ford    Focus
M0309X197RUS       1  22300.000000    Ford    Focus
O673E8197RUS       2    600.000000    Ford    Focus
8610T8154RUS       1   2000.000000    Ford    Focus
H419XE197RUS       2   8594.586466  Toyota  Corolla

[593 rows x 4 columns]

In [20]:
df.query("CarNumber in ['Y7689C197RUS', '92928M178RUS', '7788KT197RUS', 'H115YO163RUS', 'X758HY197RUS']")

              Refund          Fines  Make  Model
CarNumber
92928M178RUS       1    8594.586466  Ford  Focus
H115YO163RUS       1    2200.000000  Ford  Focus
7788KT197RUS       2   12000.000000  Ford  Focus
X758HY197RUS       2   24200.000000  Ford  Focus
X758HY197RUS       2   72600.000000  Ford  Focus
Y7689C197RUS       1   27000.000000  Ford  Focus
92928M178RUS       1     600.000000  Ford  Focus
H115YO163RUS       1    8594.586466  Ford  Focus
H115YO163RUS       2    1100.000000  Ford  Focus
7788KT197RUS       2    8594.586466  Ford  Focus
7788KT197RUS       1   20000.000000  Ford  Focus
X758HY197RUS       2  145200.000000  Ford  Focus
92928M178RUS       1    1200.000000  Ford  Focus
Y7689C197RUS       2    9000.000000  Ford  Focus
Y7689C197RUS       2   45000.000000  Ford  Focus
7788KT197RUS       2    4000.000000  Ford  Focus
Y7689C197RUS       1   36000.000000  Ford  Focus
92928M178RUS       2    3000.000000  Ford  Focus

## Make the aggregations with the make and the model
* display the median fines grouped by the make
* display the median fines grouped by the make and the model
* display the number of fines grouped by the make and the model in order to understand if we can trust the median values
* display the minimum and the maximum fines grouped by the make and the model in order to better understand the variance
* display the standard deviation of the fines grouped by the make and the model in order to better understand the variance

In [21]:
agg_func = {"Fines": ["median"]}
df.groupby(["Make"]).agg(agg_func)

             Fines
            median
Make
Audi        4200.0
BMW         6500.0
Ford        3500.0
Skoda       3250.0
Toyota      7700.0
Volkswagen  4300.0
Volvo       8500.0

In [22]:
agg_func = {"Fines": ["median"]}
df.groupby(["Make", "Model"]).agg(agg_func)

                     Fines
                    median
Make       Model
Audi       NaN      4200.0
BMW        NaN      6500.0
Ford       Focus    3500.0
           Mondeo   7650.0
Skoda      Octavia  3250.0
Toyota     Camry    7700.0
           Corolla  7700.0
Volkswagen Golf     4800.0
           Jetta    2800.0
           NaN      7400.0
           Passat   3500.0
           Touareg  5800.0
Volvo      NaN      8500.0

In [29]:
df.groupby(["Make", "Model"])["Fines"].count()

Make        Model
Audi        NaN          1
BMW         NaN          3
Ford        Focus      575
            Mondeo       6
Skoda       Octavia     48
Toyota      Camry       16
            Corolla     18
Volkswagen  Golf        20
            Jetta        6
            NaN          3
            Passat      22
            Touareg      5
Volvo       NaN          2
Name: Fines, dtype: int64

#### Медиана для штрафов многих марок основывается на маленькой выборке, вследствие чего результаты могут быть недостоверными

In [31]:
agg_func = {"Fines": ["max", "min"]}
df.groupby(["Make", "Model"]).agg(agg_func)

                            Fines
                              max     min
Make       Model
Audi       NaN        4200.000000  4200.0
BMW        NaN        8594.586466  3000.0
Ford       Focus    180000.000000   100.0
           Mondeo    46200.000000  1100.0
Skoda      Octavia  145000.000000   300.0
Toyota     Camry     22400.000000   500.0
           Corolla   34300.000000   900.0
Volkswagen Golf     168000.000000   200.0
           Jetta     46000.000000   500.0
           NaN        7900.000000  1300.0
           Passat    29700.000000   100.0
           Touareg    8594.586466   500.0
Volvo      NaN       10200.000000  6800.0

In [32]:
df.groupby(["Make", "Model"])["Fines"].agg(["std"])

                             std
Make       Model
Audi       NaN               NaN
BMW        NaN       2826.561226
Ford       Focus    15041.269437
           Mondeo   18987.329108
Skoda      Octavia  24339.742174
Toyota     Camry     6410.250654
           Corolla   9629.325617
Volkswagen Golf     36950.839950
           Jetta    17743.026799
           NaN       3674.688195
           Passat    6969.739135
           Touareg   3461.778173
Volvo      NaN       2404.163056

## Make the aggregations with the car number
* display the car numbers grouped by the number of the fines in descending order, we want to find those who most often violated the law
* select from the initial dataframe all the rows corresponding to the top-1 car number, we want to zoom in a little bit
* display the car numbers grouped by the sum of the fines in descending order, we want to find those who paid the most
* select from the initial dataframe all the rows corresponding to the top-1 car number, we want to zoom in a little bit
* display a table that answers the question: are there any car numbers that were connected to different models?

In [42]:
agg_func={"Fines": ["count"]}
df_Fines = df.groupby(["CarNumber"]).agg(agg_func)
df_Fines.sort_values(by=[("Fines", "count")], ascending=False)

             Fines
             count
CarNumber
Y7689C197RUS     4
92928M178RUS     4
7788KT197RUS     4
H115YO163RUS     3
X758HY197RUS     3
...            ...
E42577152RUS     1
E42377152RUS     1
E41977152RUS     1
E41577152RUS     1
H917TC36RUS      1

[531 rows x 1 columns]

In [44]:
df[df_Fines[("Fines", "count")] == 4]

/var/folders/jb/zkfyxcwx1_z7_qyw8llwwzxw0000gn/T/ipykernel_1814/1588729746.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[df_Fines[("Fines", "count")] == 4]

              Refund         Fines  Make  Model
CarNumber
92928M178RUS       1   8594.586466  Ford  Focus
7788KT197RUS       2  12000.000000  Ford  Focus
Y7689C197RUS       1  27000.000000  Ford  Focus
92928M178RUS       1    600.000000  Ford  Focus
7788KT197RUS       2   8594.586466  Ford  Focus
7788KT197RUS       1  20000.000000  Ford  Focus
92928M178RUS       1   1200.000000  Ford  Focus
Y7689C197RUS       2   9000.000000  Ford  Focus
Y7689C197RUS       2  45000.000000  Ford  Focus
7788KT197RUS       2   4000.000000  Ford  Focus
Y7689C197RUS       1  36000.000000  Ford  Focus
92928M178RUS       2   3000.000000  Ford  Focus

In [54]:
agg_func = {"Fines": ['sum']}
df_max_fines = df.groupby(["CarNumber"]).agg(agg_func)
df_max_fines.sort_values(by=[("Fines", "sum")], ascending=False, inplace=True)

df_max_fines

                 Fines
                   sum
CarNumber
X758HY197RUS  242000.0
9020YC197RUS  217500.0
M0279X197RUS  216000.0
Y352O8197RUS  207200.0
Y778EE197RUS  192000.0
...                ...
83218C154RUS     100.0
Y195O8161RUS     100.0
K376HE161RUS     100.0
705787163RUS     100.0
K326T8197RUS     100.0

[531 rows x 1 columns]

In [55]:
max_sum = df_max_fines[("Fines", "sum")].iloc[0]
df[df_max_fines[("Fines", "sum")] == max_sum]

/var/folders/jb/zkfyxcwx1_z7_qyw8llwwzxw0000gn/T/ipykernel_1814/2841592362.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[df_max_fines[("Fines", "sum")] == max_sum]

              Refund     Fines  Make  Model
CarNumber
X758HY197RUS       2   24200.0  Ford  Focus
X758HY197RUS       2   72600.0  Ford  Focus
X758HY197RUS       2  145200.0  Ford  Focus

In [59]:
agg_func = {"Model": ["count"]}
answer = df.groupby(["CarNumber"]).agg(agg_func)
answer.sort_values(by=[("Model", "count")], ascending=False)

             Model
             count
CarNumber
Y7689C197RUS     4
92928M178RUS     4
7788KT197RUS     4
H115YO163RUS     3
X758HY197RUS     3
...            ...
E42577152RUS     1
E42377152RUS     1
E41977152RUS     1
E41577152RUS     1
H917TC36RUS      1

[531 rows x 1 columns]

##### Are there any car numbers that were connected to different models? 

Answer: According to the table, no. Some of them have only one model.