In [109]:
import pandas as pd
import gc

## Reading the fines.csv

In [128]:
fines = pd.read_csv("../data/fines.csv")
fines

            CarNumber  Refund    Fines    Make  Model  Year
0        Y163O8161RUS       2   3200.0    Ford  Focus  1989
1         E432XX77RUS       1   6500.0  Toyota  Camry  1995
2         7184TT36RUS       1   2100.0    Ford  Focus  1984
3        X582HE161RUS       2   2000.0    Ford  Focus  2015
4        92918M178RUS       1   5700.0    Ford  Focus  2014
..                ...     ...      ...     ...    ...   ...
925      123456789RUS       2   3000.0    Ford  Focus  1980
926   ABVJS@#&$*JWRUS       2     30.0    Audi  Focus  2010
927       ABCD1234RUS       1   1000.0  Toyota   Good  2000
928    HAJR234AJGORUS       3   1500.0    Ford  Focus  2005
929  SJDIF23GJKS34RUS       3  10000.0  Toyota  Focus  2015

[930 rows x 6 columns]

## Calculation (fines/refund*year) by various methods

In [129]:
%%timeit 

def calculate():
    calculated_data = []
    for i in range(0, len(fines)):
        calculated_row = fines.iloc[i, 2] / fines.iloc[i, 1] * fines.iloc[i, 5]
        calculated_data.append(calculated_row)
    fines["loop"] = calculated_data

calculate()

30.3 ms ± 610 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [130]:
%%timeit

for index, row in fines.iterrows():
    fines.loc[index, "Iterrows"] = row["Fines"] / row["Refund"] * row["Year"]

81.3 ms ± 689 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [131]:
%%timeit

fines["Apply"] = fines.apply(lambda x: x["Fines"] / x["Refund"] * x["Year"], axis=1)

5.37 ms ± 78.1 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [132]:
%%timeit

fines["Series"] = fines["Fines"] / fines["Refund"] * fines["Year"]

97 μs ± 941 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

In [133]:
%%timeit

fines["Values"] = fines["Fines"].values / fines["Refund"].values * fines["Year"].values

51.4 μs ± 1.36 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

In [134]:
fines

,CarNumber,Refund,Fines,Make,Model,Year,loop,Iterrows,Apply,Series,Values
0,Y163O8161RUS,2,3200.0,Ford,Focus,1989,3.182400e+06,3.182400e+06,3.182400e+06,3.182400e+06,3.182400e+06
1,E432XX77RUS,1,6500.0,Toyota,Camry,1995,1.296750e+07,1.296750e+07,1.296750e+07,1.296750e+07,1.296750e+07
2,7184TT36RUS,1,2100.0,Ford,Focus,1984,4.166400e+06,4.166400e+06,4.166400e+06,4.166400e+06,4.166400e+06
3,X582HE161RUS,2,2000.0,Ford,Focus,2015,2.015000e+06,2.015000e+06,2.015000e+06,2.015000e+06,2.015000e+06
4,92918M178RUS,1,5700.0,Ford,Focus,2014,1.147980e+07,1.147980e+07,1.147980e+07,1.147980e+07,1.147980e+07
...,...,...,...,...,...,...,...,...,...,...,...
925,123456789RUS,2,3000.0,Ford,Focus,1980,2.970000e+06,2.970000e+06,2.970000e+06,2.970000e+06,2.970000e+06
926,ABVJS@#&$*JWRUS,2,30.0,Audi,Focus,2010,3.015000e+04,3.015000e+04,3.015000e+04,3.015000e+04,3.015000e+04
927,ABCD1234RUS,1,1000.0,Toyota,Good,2000,2.000000e+06,2.000000e+06,2.000000e+06,2.000000e+06,2.000000e+06
928,HAJR234AJGORUS,3,1500.0,Ford,Focus,2005,1.002500e+06,1.002500e+06,1.002500e+06,1.002500e+06,1.002500e+06
929,SJDIF23GJKS34RUS,3,10000.0,Toyota,Focus,2015,6.716667e+06,6.716667e+06,6.716667e+06,6.716667e+06,6.716667e+06

## Indexing
* get a row for a specific CarNumber, for example, ’O136HO197RUS’
* set the index in your dataframe with CarNumber
* again, get a row for the same CarNumber

In [136]:
%%timeit 
row = fines[fines["CarNumber"] == "O136HO197RUS"]

177 μs ± 4.74 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

In [45]:
row = fines[fines["CarNumber"] == "O136HO197RUS"]
row

,CarNumber,Refund,Fines,Make,Model,Year,loop,Iterrows,Apply,Series,Values
715,O136HO197RUS,2,7800.0,Toyota,Corolla,1989,7757100.0,7757100.0,7757100.0,7757100.0,7757100.0
902,O136HO197RUS,2,7800.0,Toyota,Corolla,1997,7788300.0,7788300.0,7788300.0,7788300.0,7788300.0

In [92]:
%%timeit

fines.set_index("CarNumber")

223 μs ± 35.4 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

In [137]:
fines.set_index("CarNumber", inplace=True)
fines

,Refund,Fines,Make,Model,Year,loop,Iterrows,Apply,Series,Values
CarNumber,,,,,,,,,,
Y163O8161RUS,2,3200.0,Ford,Focus,1989,3.182400e+06,3.182400e+06,3.182400e+06,3.182400e+06,3.182400e+06
E432XX77RUS,1,6500.0,Toyota,Camry,1995,1.296750e+07,1.296750e+07,1.296750e+07,1.296750e+07,1.296750e+07
7184TT36RUS,1,2100.0,Ford,Focus,1984,4.166400e+06,4.166400e+06,4.166400e+06,4.166400e+06,4.166400e+06
X582HE161RUS,2,2000.0,Ford,Focus,2015,2.015000e+06,2.015000e+06,2.015000e+06,2.015000e+06,2.015000e+06
92918M178RUS,1,5700.0,Ford,Focus,2014,1.147980e+07,1.147980e+07,1.147980e+07,1.147980e+07,1.147980e+07
...,...,...,...,...,...,...,...,...,...,...
123456789RUS,2,3000.0,Ford,Focus,1980,2.970000e+06,2.970000e+06,2.970000e+06,2.970000e+06,2.970000e+06
ABVJS@#&$*JWRUS,2,30.0,Audi,Focus,2010,3.015000e+04,3.015000e+04,3.015000e+04,3.015000e+04,3.015000e+04
ABCD1234RUS,1,1000.0,Toyota,Good,2000,2.000000e+06,2.000000e+06,2.000000e+06,2.000000e+06,2.000000e+06
HAJR234AJGORUS,3,1500.0,Ford,Focus,2005,1.002500e+06,1.002500e+06,1.002500e+06,1.002500e+06,1.002500e+06
SJDIF23GJKS34RUS,3,10000.0,Toyota,Focus,2015,6.716667e+06,6.716667e+06,6.716667e+06,6.716667e+06,6.716667e+06

In [99]:
%%timeit
fines[fines.index == "O136HO197RUS"]

135 μs ± 6.23 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

In [98]:
fines[fines.index == "O136HO197RUS"]

,Refund,Fines,Make,Model,Year,loop,Iterrows,Apply,Series,Values
CarNumber,,,,,,,,,,
O136HO197RUS,2,7800.0,Toyota,Corolla,1989,7757100.0,7757100.0,7757100.0,7757100.0,7757100.0
O136HO197RUS,2,7800.0,Toyota,Corolla,1997,7788300.0,7788300.0,7788300.0,7788300.0,7788300.0

## Downcasting
* run df.info(memory_usage=’deep’), pay attention to the Dtype and the memory usage
* make a copy() of your initial dataframe into another dataframe optimized
* downcast from float64 to float32 for all the columns
* downcast from int64 to the smallest numerical dtype possible
* run info(memory_usage='deep') for your new dataframe, pay attention to the Dtype and the memory usage

In [135]:
fines.info(memory_usage="deep")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 930 entries, 0 to 929
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   CarNumber  930 non-null    object
 1   Refund     930 non-null    int64
 2   Fines      930 non-null    float64
 3   Make       930 non-null    object
 4   Model      919 non-null    object
 5   Year       930 non-null    int64
 6   loop       930 non-null    float64
 7   Iterrows   930 non-null    float64
 8   Apply      930 non-null    float64
 9   Series     930 non-null    float64
 10  Values     930 non-null    float64
dtypes: float64(6), int64(2), object(3)
memory usage: 232.9 KB

In [138]:
optimized = fines.copy()

optimized

,Refund,Fines,Make,Model,Year,loop,Iterrows,Apply,Series,Values
CarNumber,,,,,,,,,,
Y163O8161RUS,2,3200.0,Ford,Focus,1989,3.182400e+06,3.182400e+06,3.182400e+06,3.182400e+06,3.182400e+06
E432XX77RUS,1,6500.0,Toyota,Camry,1995,1.296750e+07,1.296750e+07,1.296750e+07,1.296750e+07,1.296750e+07
7184TT36RUS,1,2100.0,Ford,Focus,1984,4.166400e+06,4.166400e+06,4.166400e+06,4.166400e+06,4.166400e+06
X582HE161RUS,2,2000.0,Ford,Focus,2015,2.015000e+06,2.015000e+06,2.015000e+06,2.015000e+06,2.015000e+06
92918M178RUS,1,5700.0,Ford,Focus,2014,1.147980e+07,1.147980e+07,1.147980e+07,1.147980e+07,1.147980e+07
...,...,...,...,...,...,...,...,...,...,...
123456789RUS,2,3000.0,Ford,Focus,1980,2.970000e+06,2.970000e+06,2.970000e+06,2.970000e+06,2.970000e+06
ABVJS@#&$*JWRUS,2,30.0,Audi,Focus,2010,3.015000e+04,3.015000e+04,3.015000e+04,3.015000e+04,3.015000e+04
ABCD1234RUS,1,1000.0,Toyota,Good,2000,2.000000e+06,2.000000e+06,2.000000e+06,2.000000e+06,2.000000e+06
HAJR234AJGORUS,3,1500.0,Ford,Focus,2005,1.002500e+06,1.002500e+06,1.002500e+06,1.002500e+06,1.002500e+06
SJDIF23GJKS34RUS,3,10000.0,Toyota,Focus,2015,6.716667e+06,6.716667e+06,6.716667e+06,6.716667e+06,6.716667e+06

In [139]:
for column in optimized.columns:
    if optimized[column].dtype == "float64":
        optimized[column] = optimized[column].astype("float32")
    elif optimized[column].dtype == "int64":
        optimized[column] = optimized[column].astype("int8")

optimized.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
Index: 930 entries, Y163O8161RUS to SJDIF23GJKS34RUS
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Refund    930 non-null    int8
 1   Fines     930 non-null    float32
 2   Make      930 non-null    object
 3   Model     919 non-null    object
 4   Year      930 non-null    int8
 5   loop      930 non-null    float32
 6   Iterrows  930 non-null    float32
 7   Apply     930 non-null    float32
 8   Series    930 non-null    float32
 9   Values    930 non-null    float32
dtypes: float32(6), int8(2), object(2)
memory usage: 198.3 KB

## Change the object type columns to the type category

In [140]:
for column in optimized.columns:
    if optimized[column].dtype == "object":
        optimized[column] = optimized[column].astype("category")

optimized.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
Index: 930 entries, Y163O8161RUS to SJDIF23GJKS34RUS
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Refund    930 non-null    int8
 1   Fines     930 non-null    float32
 2   Make      930 non-null    category
 3   Model     919 non-null    category
 4   Year      930 non-null    int8
 5   loop      930 non-null    float32
 6   Iterrows  930 non-null    float32
 7   Apply     930 non-null    float32
 8   Series    930 non-null    float32
 9   Values    930 non-null    float32
dtypes: category(2), float32(6), int8(2)
memory usage: 89.6 KB

In [141]:
optimized.memory_usage()

Index       7440
Refund       930
Fines       3720
Make        1286
Model       1310
Year         930
loop        3720
Iterrows    3720
Apply       3720
Series      3720
Values      3720
dtype: int64

## Memory clean

In [142]:
%reset_selective -f fines

In [144]:
gc.collect()

0